# Generated by Django 2.2 on 2019-05-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cclassification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='goodsimg')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('money', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
        migrations.CreateModel(
            name='Moregoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcommodity', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gcommodify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Commodity')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='gmoregoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Moregoods'),
        ),
    ]
